export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const GET_AUTH_TOKEN = "GET_AUTH_TOKEN";
export const GET_AUTH_TOKEN_SUCCESS = "GET_AUTH_TOKEN_SUCCESS";
export const GET_AUTH_TOKEN_FAILED = "GET_AUTH_TOKEN_FAILED";
export const GET_USER_ACTIVE_SUCCESS = "GET_USER_ACTIVE_SUCCESS";
export const GET_TOKEN_ACTIVE = "GET_TOKEN_ACTIVE";